### ISSUE TITLE
Screen corruption when opening table-of-contents using \lt under Mac/tmux/vim

### ISSUE THREAD

**Issue by pozix604** [lervag/vim-latex#93] opened 2015-01-08 17:28 UTC
I'm using Mac OS X Yosemite, the built-in Terminal.app, with tmux 1.9a and vim 7.4. tmux is initialized with the TERM variable set to screen-256color, which is the recommended value.

All is well until \lt is pressed and the table of contents is shown. The TOC window, and parts of the entire vim window, is corrupted. Initially blank, but if you ^F/^B to force a page refresh, the content is there. 

If you switch TERM to different values, like vt100, then the TOC displays properly but colors are not displayed properly.

I've experienced no other screen corruption issues with this setup with other vim plugins. The list that I use:

```vim
Plugin 'gmarik/Vundle.vim'     " Package management

Plugin 'amdt/vim-niji'         " Rainbow parentheses
Plugin 'ervandew/supertab'     " Tab completion
Plugin 'godlygeek/tabular'     " Alignment
Plugin 'itchyny/lightline.vim' " Pretty status line
Plugin 'kien/ctrlp.vim'        " File searching
Plugin 'scrooloose/nerdtree'   " File browser
Plugin 'tpope/vim-commentary'  " Commenting
Plugin 'salsifis/vim-transpose' " Tranpose blocks of text

Plugin 'bitc/vim-hdevtools'    " Haskell hdevtools
Plugin 'lambdatoast/elm.vim'   " Elm
Plugin 'scrooloose/syntastic'  " Syntax checking
Plugin 'travitch/hasksyn'      " Haskell
Plugin 'lervag/vim-latex'      " LaTeX
```

**Comment by nasenatmer** [comment] 2015-01-13 21:38
Hah, finally another user experiencing the same issues as me :) I reported this in #5.
In my case, I can make the whole toc visible by pressing `s` to toggle section numbering in there…

**Comment by lervag** [comment] 2015-01-17 13:39
There is probably either a bug, or there is a strange problem with vim in tmux.

Could you please verify that the problem occurs in with a minimal vimrc file (see [mine](https://github.com/lervag/dotvim/blob/master/minivimrc) for an example), just to rule out other possibilities.

**Comment by lervag** [comment] 2015-01-17 13:45
But I can report that I can reproduce the issue, both in tmux and in screen.

**Comment by lervag** [comment] 2015-01-17 13:53
With a minimal config I still get corruption, but it is much less than with my full vimrc file.

**Comment by lervag** [comment] 2015-01-17 14:03
I've found a couple of threads on Stackexchange:
http://stackoverflow.com/questions/22715071/vim-and-tmux-rendering-error
http://stackoverflow.com/questions/16374503/vim-goes-whack-with-tmux/18056690#18056690

However, none of the solutions I've found so far improves on the result I get with my minimal configuration. Just FYI, my minimal configuration for this issue is:
```vimL
set nocompatible

let &rtp = '~/.vim/bundle/vim-latex,' . &rtp

filetype plugin indent on
syntax enable

let g:latex_enabled = 1
let g:latex_default_mappings = 1

set t_Co=256
set backspace=indent,eol,start
```

**Comment by lervag** [comment] 2015-01-17 14:17
It seems like things are OK if I turn off folding.

In general, it seems like this issue is due to terminal encoding, fonts, and things that are in conflict between vim and tmux. Further, it seems like the issue is not really with vim-latex. However, I agree that this is annoying, so I will let the thread stay alive for some time to see if we can possibly find a solution, even if it is not by modifying vim-latex directly.

**Comment by nasenatmer** [comment] 2015-01-17 14:41
It definitely has to do with tmux rather than vim-latex. I just tried `\lt` with turned-off folding in both a vanilla and a tmux terminal and only the tmux one showed the rendering error. As far as I'm concerned this is a minor problem, especially due to the easy work-around of disabling and enabling section numbers in the *toc* by pressing `s`…

**Comment by lervag** [comment] 2015-01-18 12:49
I did not identify exactly which options, but I noticed that vim my standard settings the rendering errors were much more severe than with a minimal vimrc file. So much so that the `s` trick didn't work. I think it has to do with utf8 characters, but I am not sure.

**Comment by lervag** [comment] 2015-01-29 11:08
I'm closing this, as I consider it a problem with `tmux` and `screen` and perhaps `vim` itself, not with `vim-latex` specifically.

**Closed by lervag** 2015-01-29 11:08 UTC
